### ISSUE TITLE
Enabling/Disabling ScrolliViewer mdicontainer 

### ISSUE THREAD

**Issue by josecast25** [Tory05/wpfmdi#1]
Good afternoon, I am happy to greet you, I am currently using the library which seems excellent to me, however I have a query, is it possible to disable both vertical and horizontal scrolling by moving the mdiChild to the bottom of the container and to the right? so that the behavior is the same as when moving it to the left and top is to say that the container does not grow ?, Thank you and excuse me.

**Comment by Tory05** [comment]
Hello @josecast25 ,
I will look into it.

**Comment by Tory05** [comment]
Hi,

Sorry was busy with other stuff.
Added your request (not the best solution, but works as intended).
